### PR TITLE
Fast ee

### PR DESCRIPTION
**Pull request by ChangWeiTan**
I've added FastEE from my paper "FastEE: Fast Ensembles of Elastic Distances for Time Series Classification". Did some modification from my original code to support weka instances so let me know if something fails. Cheers.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi Chang, this is great, but could you PR into dev instead of master? We will look at the conflicts above, probably just some simple refactoring

**Comment by goastler** [comment]
Also, @ChangWeiTan , you need to enabled travisCI on your github. TravisCI is the tool we use to build the repo before granting PRs :)

**Comment by TonyBagnall** [comment]
if he PRs into dev it shouldnt matter? 

> Also, @ChangWeiTan , you need to enabled travisCI on your github. TravisCI is the tool we use to build the repo before granting PRs :)

i

**Comment by goastler** [comment]
> if he PRs into dev it shouldnt matter?
> 
> > Also, @ChangWeiTan , you need to enabled travisCI on your github. TravisCI is the tool we use to build the repo before granting PRs :)
> 
> i

Yes that's true, I forgot we turned off the other person needing travis :)

**Comment by ChangWeiTan** [comment]
Hi all, thanks for the comments. I have removed the generated output files (data files, .arff files etc) and change the base to dev. So do I still need to enable travis? I am not sure how to do that.

**Comment by James-Large** [comment]
Have fixed conflicts here on github, was mostly imports. There were some references to now-refactored things (e.g. weka_uea instead of weka_extras as it now is), so we may find that it does not build either once in dev or if the checks on this branch are working, but the conflicts are gone at least, build issues will require a second look

**Pull request merged**
