### PR TITLE
ts reader now uses scanner

### PR DESCRIPTION
**Pull request by ABostrom**
This is the draft PR for the new and improved TS Reader that uses scanner. 

Needs testing thoroughly. but works on both the univariate and multivariate datasets.

Next up is checking the weird special character cases and scientific types.

### CODE REVIEW

**Comment by ABostrom** [comment]
@MatthewMiddlehurst let me know. But i think we're good to go.

**Review by MatthewMiddlehurst — APPROVED** [review]
No issues if it passes on the archive .ts files. When we get the sktime version of HC2 running I will most likely revisit running our stuff via jar using both .arff and .ts so can road test it a bit more then.

**Comment by ABostrom** [comment]
@MatthewMiddlehurst any idea hwy ci is failing. doesn't give me a lot to go on.

**Comment by MatthewMiddlehurst** [comment]
No, didnt even notice we had them again past this pr. Probably more likely its an issue with the test than the code.

**Review by TonyBagnall — APPROVED** [review]

**Pull request merged**
