### PR TITLE
Proximity Forest

### PR DESCRIPTION
**Pull request by goastler**
Proximity Forest with train estimation. Currently PF cross validation doesn't work, fix to come later. OOB and OOB with rebuild do work, however.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
could you move all the additions to ClassifierLists to a local version? I keep a package called development locally so I dont bloat the "official" ClassifierLists
image

**Comment by TonyBagnall** [comment]
@James-Large could you take a look at the changes to evaluation package to ensure you are ok with them?

**Comment by TonyBagnall** [comment]
I dont think we want all the gunPointLoad stuff that has appeared in DatasetLoading, keep that local too please

**Comment by TonyBagnall** [comment]
Can you explain the OutOfBagEvaluator ? I'm not sure how this generalises, OOB is something done internally and is specific to forests. How would it work with for example ShapeletTransformClassifier?

**Comment by goastler** [comment]
> Can you explain the OutOfBagEvaluator ? I'm not sure how this generalises, OOB is something done internally and is specific to forests. How would it work with for example ShapeletTransformClassifier?

`OutOfBagEvaluator` just keeps things consistent. We've got the `CrossValidationEvaluator` therefore it made sense to have one for OOB so classifiers can use it as and when required. In a nutshell, it takes a classifier and a set of data, partitions the data into the in-bag train data and out-of-bag test data, builds the classifier on the in-bag train data and tests on the out-of-bag test data and returns a classifier results object. As far as I understand, the OOB evaluation fits nicely into the Evaluator system @James-Large made. I have no problem if this needs to be moved out of the top level evaluators package though (or needs alteration to fit with the `Evaluator` system). 

I don't see how it would be used with ShapeletTransformClassifier exactly, unless `ShapeletTransformClassifier` was a constituent in an ensemble. I.e. in a heterogeneous ensemble instead of 10 fold cross validating each constituent I could use the `OutOfBagEvaluator` instead as a quicker alternative to discover weights for each constituent. The OutOfBagEvaluator use case is pretty much the same as the `CrossValidationEvaluator`

**Comment by goastler** [comment]
> I dont think we want all the gunPointLoad stuff that has appeared in DatasetLoading, keep that local too please

I've used this in unit testing. We've got ItalyPowerDemand in the DatasetLoading already but I wanted to add a couple more datasets to be sure the unit tests are running correctly (specifically the data dependent ones)

**Comment by goastler** [comment]
> could you move all the additions to ClassifierLists to a local version? I keep a package called development locally so I dont bloat the "official" ClassifierLists
> image

I assumed you would want the ones in the list at the moment for running PF with either CV or OOB or OOB with rebuild? I can remove them if not

**Comment by TonyBagnall** [comment]
ok thats all fine then. The OOB can stay, but it is a bit weird to have it external, its not usual to want to find the OOB of as single base classifier, rather you find it for the ensemble. However, I realise that you are experimenting with weighting components. I may add some comments to explain at a later date.
So if you clean up ClassifierLists (I will also clean the rest soon) and @James-Large is ok with the other changes, then I think its good to go

**Comment by goastler** [comment]
Okay sounds good, I'll remove the configs from clsf lists

**Comment by James-Large** [comment]
Going through it, on OOBEvaluator first, seem like it's effectively the same as SingleSampleEvaluator, but keeps access to the data splits? SingleSample uses the resampleInstances and doesn't look at it further, if you need to split in a particular way and want access to the in/out of bag indices etc. I'm fine with all of this

Would just say have it extend SamplingEvaluator instead of just Evaluator, looks like you've got the methods basically there already. Difference being only that SamplingEvaluators will train/test on the single instances object given, instead of requiring a predefined train/test split

**Comment by James-Large** [comment]
More wrapped/automatic data loading helpers is probs always good in my opinion. 10000% add java doc to the new loading methods to warn that they return a single instances object with train and test merged, and/or change the naming pattern to add merged to the func names or something

**Comment by James-Large** [comment]
Pretty much all the rest is distance based stuff which is up to George either way

Things added to the higher level utils are all fine, these will all need an overhaul at some point (tidying/organising/documenting) when the data format comes in at some stage

**Pull request merged**
