### PR TITLE
Dimension independent transformer implementation

### PR DESCRIPTION
**Pull request by Multivin12**
Implementation of the Dimension Independent Transformer which is aimed to address issue #390

### CODE REVIEW

**Comment by TonyBagnall** [comment]
hi vincent, looks good, couple of comments
1. could you add @author tag at the top of the file and add a comment about what the class does? 
2. I think I'd like a default constructor with the transform set to PAA, not sure about that though
3. There is no fit method so will not be usable with a TrainableTransformer, but I'm not sure how to resolve that. I'll discuss with Aaron.

**Comment by ABostrom** [comment]
Looks fine, the only thing I think you need to do @Multivin12 is clone the transformer and use it separately for each dimension. Transformers that autofit will need to do this on an individual dimensional basis.

**Comment by Multivin12** [comment]
@ABostrom I guess would this be needed to be done in transform or the constructor?

**Comment by TonyBagnall** [comment]
so where and if to clone is a good question, as is how to clone! 
1. If we always clone a transformer for each dimension, its a bit redundant if its not Trainable. But its not so great putting in a test of is TrainableTransformer.  My first thought is to have an array of Transformer, but then just copy the reference unless the Transformer is Trainable. 
2. If we do it in the constructor, we cannot refit, but if we do it in Transform, we may refit every time. hmmmm, shall we defer this by making it not work with TrainableTransformer (throw an exception in the constructor)?

**Comment by Multivin12** [comment]
Yeah I don't mind throwing an exception if the transformer is a TrainableTransformer I'll quickly implement that now.

**Comment by ABostrom** [comment]
My personal feeling on in constructor vs. transform is do it in the constructor. Make it so you build the transformer, and if you want to change the transformer on dimensions then just build a new object. This only wraps the real work, so it shouldn't be performance critical to create the object and clone etc.

**Pull request merged**
