### PR TITLE
Convolution feature

### PR DESCRIPTION
**Pull request by ABostrom**
#434 
This feature implements Convolutions to aid in the development of the ROCKET classifier.

Transformer contains static functions that perform 1D or 2D convolutions as required.

### CODE REVIEW

**Comment by James-Large** [comment]
Can 1d convs be padded too?

**Comment by James-Large** [comment]
Looks solid, yeah I don't think we really need to bother with the weka equivalents any more, certainly not beyond just a conversion to timeseriesinstances internally and using those. Could just put a conversion in and all to the overload here? https://github.com/uea-machine-learning/tsml/pull/437/files#diff-24ffdc5c1463d73370f359311328d05aR61

**Comment by James-Large** [comment]
I'll do here

**Comment by ABostrom** [comment]
This is what i will look todo in a future feature, when we start using TSInstances more, and others are using them more, then we can auto convert to TSInstances.

**Comment by ABostrom** [comment]
I reckon you'll need the import and it won't compile

**Comment by James-Large** [comment]
Ah, the danger commit strikes again, always a bad idea

**Pull request merged**
